branches:
  only:
    - "master"
    - "develop"
language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
install:
  - pip install . --use-mirrors
  - pip install nose --use-mirrors
script: nosetests --exe -v